### ISSUE TITLE
SLO test in kubernetes

### ISSUE THREAD

**Issue by rekby** [ydb-platform/ydb-python-sdk#108]
Run SLO tests in kubernetes

- [ ] With some special action
- [ ] Auto (PR/Merge/Daily)

**Comment by zeruk** [comment]
@rekby 
CI example is here: https://github.com/ydb-platform/ydb-nodejs-sdk/blob/main/.github/workflows/slo.yml
Workload sample and description is here: https://github.com/ydb-platform/ydb-nodejs-sdk/tree/main/slo-workload
As you can see from the repository, you will need to create a directory for the workload package and provide a Dockerfile inside it.
