### ISSUE TITLE
ImportError: attempted relative import with no known parent package

### ISSUE THREAD

**Issue by ComradeAx0n** [ydb-platform/ydb-python-sdk#14]
Ошибка конкретно этого проекта не касается, но может подскажите что делать или почитать. Я не особо шарю за python, а гугление толкого ничего не дал.

Шел по сценарию в практикуме и при запуске тестового приложения вываливается ошибка.
```bash
➜  basic_example_v1 git:(main) ll
total 24K
-rw-rw-r-- 1 ubuntu ubuntu 6.8K Feb  8 16:42 basic_example_data.py
-rw-rw-r-- 1 ubuntu ubuntu 9.6K Feb  8 16:42 basic_example.py
-rw-rw-r-- 1 ubuntu ubuntu  917 Feb  9 13:36 __main__.py
➜  basic_example_v1 git:(main) python3 __main__.py
Traceback (most recent call last):
  File "__main__.py", line 3, in <module>
    from . import basic_example
ImportError: attempted relative import with no known parent package
➜  basic_example_v1 git:(main) pwd
/home/ubuntu/vscode/yandex-prak/ydb-python-sdk/examples/basic_example_v1
```

Версия Python 3.8.10
Урок с практикума https://practicum.yandex.ru/trainer/ycloud/lesson/bb84c932-2cbd-4737-9d56-2f7952462493/

**Comment by gridnevvvit** [comment]
Скорее всего проблема в том, что прямо сейчас отсутствует __init__.py файл в примере, кажется во время рефакторингов он пропал.

**Comment by ComradeAx0n** [comment]
По идее достаточно ведь пустой файл __init__.py закинуть в ту же директорию, чтобы заработало?
Я вроде пробовал, но проку не было.

**Comment by gridnevvvit** [comment]
fixed by https://github.com/ydb-platform/ydb-python-sdk/pull/18
