### ISSUE TITLE
bug: please remove requierement "Please specify commit or tag version"  from bug template

### ISSUE THREAD

**Issue by maximyurchuk** [ydb-platform/ydb-python-sdk#458]
# Bug Report

**YDB Python SDK version:**
-
**Environment**
-
**Current behavior:**
When I file a bug it is necessary to specify "commit or tag version" 

But I don't know any commit or tag, the only thing I know is a version from pypi

See https://github.com/ydb-platform/ydb-python-sdk/blob/c383b407f7033fb94618e94c4000438b1c080a76/.github/ISSUE_TEMPLATE/01_BUG_REPORT.md?plain=1#L14 

**Expected behavior:**
Version from pypi must be the primary way to specify version and file a bug

**Steps to reproduce:**
Just file a bug!

**Related code:**
https://github.com/ydb-platform/ydb-python-sdk/blob/c383b407f7033fb94618e94c4000438b1c080a76/.github/ISSUE_TEMPLATE/01_BUG_REPORT.md?plain=1#L14 

**Other information:**

**Comment by vgvoleg** [comment]
Here we operate with github terms - commits and tags. Tags are used to identify specific versions of a project.
There are many ways to install python package and pypi is not the only one. 
But don't worry, we don't use any other mechanism as github tag to create pypi releases - pypi version represents a github tag with the same name.
