### ISSUE TITLE
support snapshot read only transaction mode

### ISSUE THREAD

**Issue by gridnevvvit** [ydb-platform/ydb-python-sdk#53]
API reference: https://github.com/ydb-platform/ydb-api-protos/pull/10

[proto](https://github.com/ydb-platform/ydb-api-protos/blob/667c41254584002e08fab78582f9f0f53d25c842/protos/ydb_table.proto#L713)

**Comment by Valeria1235** [comment]
https://github.com/ydb-platform/ydb-python-sdk/pull/88
