### ISSUE TITLE
AttributeError: 'PrimitiveType' object has no attribute 'item' in sqlalchemy

### ISSUE THREAD

**Issue by gridnevvvit** [ydb-platform/ydb-python-sdk#57]

**Comment by gridnevvvit** [comment]
traceback
` File "ydb/public/sdk/python/ydb/sqlalchemy/__init__.py", line 256, in get_columns
    "type": _get_column_type(column.type),
  File "ydb/public/sdk/python/ydb/sqlalchemy/__init__.py", line 195, in _get_column_type
    if isinstance(t.item, ydb.DecimalType):
AttributeError: 'PrimitiveType' object has no attribute 'item'`

**Comment by Valeria1235** [comment]
fixed in https://github.com/ydb-platform/ydb-python-sdk/pull/232
